language: php

php: 7.1

install:
    - composer install

script:
    - vendor/bin/statie generate source
    - cp -rf source/svatba output

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: output
    on:
        branch: master
